on:
  pull_request:
    branches: [ "main" ]

name: validate-branch-name

permissions:
  contents: read

jobs:
  lint:
    name: Validate Branch Name
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate Branch Name
      uses: launchbynttdata/actions-lcaf-branch_name@v0
